// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReviewWebsiteProject;

namespace ReviewWebsiteProject.Migrations
{
    [DbContext(typeof(ArcadeContext))]
    [Migration("20200220182942_RemovedReviewColumnFromProduct")]
    partial class RemovedReviewColumnFromProduct
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ReviewWebsiteProject.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Yellow fruit-eating monster",
                            Image = "/img/pacman.jpg",
                            Name = "Pac-Man"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Save the Realms from certain doom",
                            Image = "/img/GauntletLegends.jpg",
                            Name = "Gauntlet Legends"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Dig and dug",
                            Image = "/img/digdug.jpg",
                            Name = "DigDug"
                        });
                });

            modelBuilder.Entity("ReviewWebsiteProject.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Tasty",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            Content = "Not Tasty",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 3,
                            Content = "Tastiest",
                            ProductId = 1
                        });
                });

            modelBuilder.Entity("ReviewWebsiteProject.Models.Review", b =>
                {
                    b.HasOne("ReviewWebsiteProject.Models.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
